/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LuyenTap4_De2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hawin
 */
public class DienThoaiView extends javax.swing.JFrame {

    /**
     * Creates new form DienThoaiView
     */
    ArrayList<DienThoai> list = new ArrayList<>();
    DienThoaiService qldt = new DienThoaiService();
    DefaultTableModel defaultTableModel;
    String filename = "DienThoai.txt";

    public DienThoaiView() {
        ArrayList<DienThoai> list = qldt.getListDienThoai();
        initComponents();
        loadData(list);
        cuoi();

    }

    void loadData(ArrayList<DienThoai> list) {
        int STT = 1;
        defaultTableModel = (DefaultTableModel) tblDienThoai.getModel();
        defaultTableModel.setRowCount(0);
        for (DienThoai dienThoai : list) {
            defaultTableModel.addRow(new Object[]{
                STT++,
                dienThoai.getMa(),
                dienThoai.getHang(),
                dienThoai.getMauSac(),
                dienThoai.getGia(),
                dienThoai.getBoNho()
            });
        }
    }

    public void cuoi() {
        int i = tblDienThoai.getRowCount() - 1;
        String ma = (String) tblDienThoai.getValueAt(i, 1);
        txtMa.setText(ma);
        String hang = (String) tblDienThoai.getValueAt(i, 2);
        cboHang.setSelectedItem(hang);
        String mauSac = (String) tblDienThoai.getValueAt(i, 3);
        if (mauSac.equals("Đen")) {
            rdDen.setSelected(true);
        } else if (mauSac.equals("Trắng")) {
            rdTrang.setSelected(true);
        } else {
            rdVang.setSelected(true);
        }
        Integer gia = (Integer) tblDienThoai.getValueAt(i, 4);
        String giaDT = String.valueOf(gia);
        txtGia.setText(giaDT);
        String boNho = (String) tblDienThoai.getValueAt(i, 5);
        txtBoNho.setText(boNho);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtBoNho = new javax.swing.JTextField();
        cboHang = new javax.swing.JComboBox<>();
        rdDen = new javax.swing.JRadioButton();
        rdTrang = new javax.swing.JRadioButton();
        rdVang = new javax.swing.JRadioButton();
        txtGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDienThoai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUẢN LÝ ĐIÊN THOẠI");

        jLabel2.setText("Mã: ");

        jLabel3.setText("Hãng: ");

        jLabel4.setText("Bộ nhớ: ");

        jLabel5.setText("Màu sắc: ");

        jLabel6.setText("Giá: ");

        cboHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "SamSung", "Oppo" }));

        buttonGroup1.add(rdDen);
        rdDen.setText("Đen");

        buttonGroup1.add(rdTrang);
        rdTrang.setText("Trắng");
        rdTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTrangActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdVang);
        rdVang.setText("Vàng");

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnGhiFile.setText("Ghi file");
        btnGhiFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGhiFileMouseClicked(evt);
            }
        });
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        btnMoFile.setText("Mở file");
        btnMoFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoFileMouseClicked(evt);
            }
        });

        tblDienThoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Hãng", "Màu sắc", "Giá", "Bộ nhớ"
            }
        ));
        tblDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDienThoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDienThoai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBoNho, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboHang, 0, 92, Short.MAX_VALUE)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdDen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdVang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGia))
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnThem)
                .addGap(90, 90, 90)
                .addComponent(btnGhiFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoFile)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdDen)
                    .addComponent(rdTrang)
                    .addComponent(rdVang))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cboHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBoNho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnGhiFile)
                    .addComponent(btnMoFile))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTrangActionPerformed

    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiFileActionPerformed

    private void tblDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDienThoaiMouseClicked
        // TODO add your handling code here:
        int i = tblDienThoai.getSelectedRow();
        String ma = (String) tblDienThoai.getValueAt(i, 1);
        txtMa.setText(ma);
        String hang = (String) tblDienThoai.getValueAt(i, 2);
        cboHang.setSelectedItem(hang);
        String mauSac = (String) tblDienThoai.getValueAt(i, 3);
        if (mauSac.equals("Đen")) {
            rdDen.setSelected(true);
        } else if (mauSac.equals("Trắng")) {
            rdTrang.setSelected(true);
        } else {
            rdVang.setSelected(true);
        }
        Integer gia = (Integer) tblDienThoai.getValueAt(i, 4);
        String giaDT = String.valueOf(gia);
        txtGia.setText(giaDT);
        String boNho = (String) tblDienThoai.getValueAt(i, 5);
        txtBoNho.setText(boNho);
    }//GEN-LAST:event_tblDienThoaiMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
//        DienThoai dt1 = new DienThoai();
        String ma = txtMa.getText();
        String hang = cboHang.getSelectedItem().toString();
        String mauSac = "";
        if (rdDen.isSelected()) {
            mauSac = "Đen";
        } else if (rdTrang.isSelected()) {
            mauSac = "Trắng";
        } else {
            mauSac = "Vàng";
        }
        String giaDT = txtGia.getText().trim();

        String boNho = txtBoNho.getText();

        if (ma.trim().isEmpty() || hang.trim().isEmpty() || mauSac.trim().isEmpty() || giaDT.isEmpty() || boNho.trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Ko đc để trống");
        } else {
            Integer gia = Integer.valueOf(giaDT);

            if (gia < 100) {
                JOptionPane.showMessageDialog(this, "Phải là số nguyên dương và lớn hơn 100");
            } else {
                DienThoai dt = new DienThoai(ma, hang, mauSac, boNho, gia);
                Boolean check = qldt.add(dt);
                if (check) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    loadData(qldt.getListDienThoai());
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
        }


    }//GEN-LAST:event_btnThemMouseClicked

    private void btnGhiFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGhiFileMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, qldt.ghiFile(filename));
    }//GEN-LAST:event_btnGhiFileMouseClicked

    private void btnMoFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoFileMouseClicked
        // TODO add your handling code here:
        loadData(qldt.getListDienThoai());
        qldt.getListDienThoai().clear();
        JOptionPane.showMessageDialog(this, qldt.docFile(filename));
        loadData(qldt.getListDienThoai());
    }//GEN-LAST:event_btnMoFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DienThoaiView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DienThoaiView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DienThoaiView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DienThoaiView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DienThoaiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdDen;
    private javax.swing.JRadioButton rdTrang;
    private javax.swing.JRadioButton rdVang;
    private javax.swing.JTable tblDienThoai;
    private javax.swing.JTextField txtBoNho;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
